### ISSUE TITLE
API

### ISSUE THREAD

**Issue by kubukoz** [lazamar/nix-package-versions#16]
Hi,

Would it take a lot of effort to add a restful API to this site? It would enable building more tools on top of the existing index, e.g. a CLI that produces expressions with a simple command (or a site that exposes URLs that return such expressions - something I'd be interested in building into [nix-milk](https://github.com/kubukoz/nix-milk)).

What I think would be sufficient is an endpoint that takes e.g. `hello` + `1.0.0.2` (specific number, for starters) and produces something like

```json
{
  "name": "hello-1.0.0.2",
  "nixpkgs_url": "https://github.com/NixOS/nixpkgs/archive/c82b46413401efa740a0b994f52e9903a4f6dcd5.tar.gz"
}
```

Then the rest of the tools could get the SHA of that nixpkgs version, and produce a reproducible expression, etc.

**Comment by lazamar** [comment]
Yeah, I think an API would be reasonable. Would you like to have a go at it?

The place look at is `https://github.com/lazamar/nix-package-versions/blob/master/src/App/Server.hs`. 

You could create a new endpoint or just return a different result if the `Content-Type` header is `application/json`. The `getVersions` function in that file does what will be needed.

The goal of the tool is to allow you to search a package by name to find the possible versions, so the endpoint would have to return a list of all versions and urls available for a package rather than taking a version and returning only one url.

My only fear with it is that this service runs on a rather weak machine and any moderately heavy automated traffic could bring it down. 
But I could keep an eye on it and cross that bridge when we get there.

**Comment by kubukoz** [comment]
I can give it a try, although I'm not _that_ comfortable in my Haskell, so we'll see how it goes :)

**Comment by lazamar** [comment]
As there was no update I'm closing this.
