### ISSUE TITLE
`nix-env` installation instructions should use attr path

### ISSUE THREAD

**Issue by lilyball** [lazamar/nix-package-versions#18]
The `nix-env` installation instructions for a package currently uses the package name. For example, [`jq-1.5`](https://lazamar.co.uk/nix-versions/?package=jq&version=1.5&fullName=jq-1.5&keyName=jq&revision=a3962299f14944a0e9ccf8fd84bd7be524b74cd6&channel=nixpkgs-unstable#instructions) says:

> Install `jq` with `nix-env`.
>
> ```
> nix-env -i jq-1.5 -f https://github.com/NixOS/nixpkgs/archive/a3962299f14944a0e9ccf8fd84bd7be524b74cd6.tar.gz
> ```

This is going to be slow. It should instead suggest a command like

```
nix-env -iA jq -f https://github.com/NixOS/nixpkgs/archive/a3962299f14944a0e9ccf8fd84bd7be524b74cd6.tar.gz
```

This is much faster and unambiguous, and also matches the behavior of the other instructions.

**Comment by lazamar** [comment]
Cool, so that would be using only the `pname` field in https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/development/tools/jq/default.nix

But how would this work for packages that make multiple versions available in the same nixpkgs revision?

The idea is that we want the newest revision where a package version can be found. So imagine that the default version of `jq` is `1.5`. That's what will be installed with `nix-env -iA jq`. But let's say that version `1.4` is also available in the same revision. We want the command to work for installing version `1.4` in that revision too.

Do you know how we could handle that?

**Comment by lilyball** [comment]
It's not the `pname` field, it's the attribute path. It's the exact same thing that `nix-shell -p` uses.

**Comment by lazamar** [comment]
Got it. Thanks!
