### ISSUE TITLE
Storage requirements

### ISSUE THREAD

**Issue by kerscher** [lazamar/nix-package-versions#21]
# Problem description

When considering if I can deploy `nix-package-versions-exe` on infrastructure I operate
I can't be sure I'll have enough vCPUs, memory and disk space to handle its load.

# Suggested implementation

- Update `README.md` with
  - example storage requirements for some arbitrary `nixpkgs` range for `--update-versions` - e.g. all of 2021; last 12 months etc.
  - update procedure and its storage impact

I can give it a go at running this and progressively try longer ranges until I can see values for [the local database and cache sizes](https://github.com/lazamar/nix-package-versions/blob/master/src/App/Main.hs#L176-L177) and then issue you a pull request.
If you have that information at hand already it'd be probably easier for you to create it directly.

**Comment by lazamar** [comment]
This is something that interests me too as currently I have to manually run the update script locally and upload the updated database to my DigitalOcean host because the host OOMs trying to run the update itself. It is a very small machine with only 2GB of memory.

The storage requirements are not high. The entire current database in the live nix-package-versions, which goes back to January 2017 weighs `673M`.

The database update script does some github queries and then afterwards asks Nix to create a big json file with info about  a revision. I think Nix's creation of this big JSON uses quite a bit of memory. I usually do that on machine with 16GB of RAM.

I remember trying to decrease the amount of these JSON the script would do in parallel, but even then it needed more than 2GB of RAM.
