### ISSUE TITLE
Use git log instead of downloading xy tar archives

### ISSUE THREAD

**Issue by ostrolucky** [lazamar/nix-package-versions#29]
I've checked out the code and apparently for every commit you download separate archive of whole pkgs repo. I would suggest to just download git repo once, then you can run git pull on each execution to ensure you have latest changes and run git log & git checkout. That should be much more efficient.

**Comment by lazamar** [comment]
That would probably be faster for one commit, but with the current approach I can process multiple commits in parallel and that is an advantage.

For a bit of context, after the content for a commit is downloaded, nix does some processing of the result to show the JSON I want. This processing takes a couple of minutes, while downloading the content takes about 10 seconds or so.
So it ends up being faster to just download everything.
This would also only be relevant during version updates, which I only do once every five weeks or so and leave it running overnight so speed is not a big deal.

Another point worth mentioning is that keeping a cloned repo could is more cumbersome than downloading things and in this project I want to optimise for ease of maintenance more than for speed.

**Comment by milahu** [comment]
wow, what a waste of network traffic and cpu time

https://github.com/lazamar/nix-package-versions/blob/3b7d0c6ca07f0d3a59353550c6f7b0f64d8c0f97/src/Nix.hs#L191-L197

30% of all commit subjects have the format
`[a-zA-Z0-9_.-]+: ([^ ]+ -> [^ ]+|init at [^ ]+)`
from where we can parse package updates

```
$ git rev-list --count master
623247

$ git log --format=format:"%H %s" | grep -E '^.{40} [a-zA-Z0-9_.-]+: ([^ ]+ -> [^ ]+|init at [^ ]+)$' | wc -l
191506

$ git log --format=format:"%H %s" -- pkgs/applications/networking/browsers/tor-browser/default.nix | grep -E '^.{40} [a-zA-Z0-9_.-]+: ([^ ]+ -> [^ ]+|init at [^ ]+)$'
a59b34e6c9c182c7a561bf0a1e709ca1f8162ca1 tor-browser: 13.0.13 -> 13.0.14
7df86308d9830a4571fa040233cdb6b2384ae970 tor-browser: 13.0.12 -> 13.0.13
ad13fd31a6b90b22d2051463d2d999d88145ebb2 tor-browser: 13.0.11 -> 13.0.12
a1f2dbfacd97e8f8abf4c5c16d3934ac9275f93b tor-browser: 13.0.10 -> 13.0.11
39382e6c8f2f028372b745d24bb3f3f22d94fbb2 tor-browser: 13.0.9 -> 13.0.10
dfe6be1209bb7b9ac0382c2543692e0747230fd3 tor-browser: 13.0.8 -> 13.0.9
3873eb4bcd61d8835d4b9bc264e5ed6ecb8cea39 tor-browser: 13.0.6 -> 13.0.8
08d365746203d2de4b8ae1efdeba5e27c1cea871 tor-browser: 13.0.5 -> 13.0.6
ef557f03443850cbbb44a2ef327afd78bfef7cf4 tor-browser: 13.0.1 -> 13.0.5
de2ced25d80d8bf8d5b9e3a2b4848d7fb0edefba tor-browser: 13.0 -> 13.0.1
65e47cc67012aaa933823b60a30d5272b67b44e5 tor-browser: 12.5.6 -> 13.0
b6a2c2b937162f37da7314af68054111b2454e27 tor-browser: 12.5.5 -> 12.5.6
```

the commit subject can be wrong (typos), so this still should be verified like

```
$ git show a59b34e6c9c182c7a561bf0a1e709ca1f8162ca1 | grep -m1 '^+.*"13.0.14"'
+  version = "13.0.14";
```

... but that is still 1000x faster than `nix-env -q`

a more efficient updater could run more often, maybe 1x per week

related: does `Nix.hs` do incremental updates?
usually the git history of nixpkgs is immutable

**Comment by lazamar** [comment]
Yeah, rev-list is faster but it is neither reliable nor contain all the information we would need.
This project actually started with me using `git rev-list`. I wrote about it in the project's [blog post](https://lazamar.github.io/download-specific-package-version-with-nix/).

The program does work incrementally, which means that building the database for the first time can takes long, but updating it every few weeks takes just a couple of minutes. So optimising the algorithm is not really worthwhile.

There are two reasons why I don't update the db more often:
1. Packages don't change versions that often anyway, so there is no need for very granular tracking
2. I run this on a very cheap Digital Ocean machine which is able to run the server, but doesn't have enough resources to run the Nix commands required to update the db. This means that I have to do the updating somewhere else and upload the db to that machine. However, I don't have a Linux machine of my own, so every time I have to spin-up a Linux machine, get the project into it, copy the live db into it, update the db, then upload the db to the server.

Reason no 2 can be addressed by using a larger machine, then a cron job could update the db quite frequently. However, I don't want to pay for that 🙃. Also, reason no 1 means its not a big deal.

**Comment by milahu** [comment]
> rev-list is faster

yepp, the single-threaded `nix-env -q` takes 240 seconds on my 2.4 GHz cpu
grepping through git history should be 100x faster

> rev-list is faster but it is neither reliable nor contain all the information

what is missing?
we get: revision, date, pname, version

ok, the nixpkgs attribute is missing
but the attribute-filepath mapping can be created once
and is updated only when the file is moved

```
nix-repl> python3Packages.requests.meta.position
"/nix/store/4ab6vrcph07w6ra79bc04fy8bbcmb9r0-source/pkgs/development/python-modules/requests/default.nix:88"
```

```
$ git show a59b34e6c9c182c7a561bf0a1e709ca1f8162ca1 -U99999999 | grep -E -e '^Date: ' -e 'pname = "' -e '^[+-].*version = "'
Date:   Tue Apr 16 19:25:09 2024 +0200
-  version = "13.0.13";
+  version = "13.0.14";
   pname = "tor-browser";
```

loop over all commits from old to new, to parse package updates

first try this fast path: require one version change and one pname (can change) (1 second)

if one of the assertions fail, fallback to the slow path:
mount the commit with `git worktree add $rev $rev` (40 seconds for 40K files) (or use [gitfuse](https://github.com/davesque/gitfuse))
and run nix eval with `nix-env -q -f $rev` (240 seconds)

> every time I have to spin-up a Linux machine

ideally this should run in github actions

> the project's [blog post](https://lazamar.github.io/download-specific-package-version-with-nix/)

> This amounts to 542Mb which I store in an SQLite database

yepp, that should work on github.
github repo size has a soft limit of 5 GB, and a hard limit of 10 GB
file size: soft limit 50 MB, hard limit 100 MB, so that would need sharding
example: my [opensubtitles-scraper-new-subs](https://github.com/milahu/opensubtitles-scraper-new-subs) repo has 3 GB = 150 x 20 MB

> I run this on a very cheap Digital Ocean machine which is able to run the server, but doesn't have enough resources to run the Nix commands required to update the db.

ideally the frontend should be static html files on github pages
with `/{nixpkgs_branch}/{pkg_attr}.html` paths

should i make a proof of concept?

**Comment by lazamar** [comment]
Those are interesting ideas, and I like the exercise. But first let's take a step back.
What problem are you trying to solve?

**Is the goal to make it faster?**
Having the program be able to build the database from 0 very quickly is a cool thing, but that is not the main goal of this project. The goal is to make the data quickly accessible. It's fine if it takes a while to build from 0.

Also, building from 0 only happens when I change something in the db schema, which is very rare. Incremental builds are the norm and those are pretty quick.

If it were a small change I'd be all for the performance gains, but this approach would add a significant amount of complexity to solve a problem that is already solved in about 10 lines of code. The proposed algorithm is also rather subtle. It is based on heuristics and it seems that there would be plenty of ways for weird or wrong commits to nixpkgs to break it. Debugging it would also not be trivial. I really don't think the speed is worth the trade-off in complexity.

**Is the goal to support more frequent updates?**
As I mentioned above, I don't see the need for more frequent updates. Almost all packages have update cycles much longer than 5 weeks.

**Is the goal to make my life easier?**
Now I do like that goal! But I'm afraid the increase in complexity wouldn't quite achieve that.

But the GH actions idea could work. The current script when running in a GH action could just connect to the database and perform an incremental update. It should be fine for actions to run repeatedly given db updates are idempotent. That would work.

I also like the idea of using GH pages, but one per package would mean a lot of files. Your code sample shows 191506 in a single branch of nixpkgs. The project currently tracks 22 branches.
One option would be to have files with JSON objects, one for each package. The object then contains all versions and hashes for that package. Then we have one HTML file, which will fetch the appropriate JSON file according to the package being viewed. This should work fine from GH pages.

If you feel like having a go at making this work from GH pages I'd be happy to show the ropes wherever needed.

**Comment by milahu** [comment]
> What problem are you trying to solve?

all of them ; )

early draft in [nixpkgs-package-version-log](https://github.com/milahu/nixpkgs-package-version-log)

example output: [loop-commits.py.head1000.txt](https://github.com/milahu/nixpkgs-package-version-log/raw/main/docs/loop-commits.py.head1000.txt)

spoiler: i will not finish this project
"incremental parsing of nixpkgs without nix eval" should be in the interest of "the nix community"
so i hope that "someone" will continue this project...
(im banned from there, so i cant promote it)

> this approach would add a significant amount of complexity

yes. trading cpu time for developer time
short term investment for better efficiency in the long term

> The proposed algorithm is also rather subtle. It is based on heuristics

most files in nixpkgs are "package files" (leaf nodes)
they have one `pname` and one `version`, so updates are easy to parse

some files are "scope files" (branch nodes)
which produce a scope of many packages
these are needed to parse attributes of packages

```
pkgs/top-level/all-packages.nix
pkgs/top-level/python-packages.nix
pkgs/development/node-packages/node-packages.nix
pkgs/applications/editors/vim/plugins/generated.nix
pkgs/applications/editors/vscode/extensions/default.nix
...
```

usually these "scope files" are large nix files
for example `hackage-packages.nix` with 13 MB = 10x larger than `all-packages.nix`

```
$ find pkgs/ -name '*.nix' | xargs du -b | sort -n -r | head -n10
12766839        pkgs/development/haskell-modules/hackage-packages.nix
3986976 pkgs/development/r-modules/cran-packages.nix
3728940 pkgs/development/node-packages/node-packages.nix
2726640 pkgs/development/lisp-modules/imported.nix
2511686 pkgs/tools/typesetting/tex/texlive/tlpdb.nix
1352110 pkgs/top-level/all-packages.nix
1032034 pkgs/top-level/perl-packages.nix
721718  pkgs/development/compilers/elm/packages/node/node-packages.nix
699541  pkgs/tools/typesetting/tex/texlive/fixed-hashes.nix
612810  pkgs/top-level/python-packages.nix
```

see also [nixpkgs-large-nix-files-top1000.txt](https://github.com/milahu/nixpkgs-package-version-log/raw/main/docs/nixpkgs-large-nix-files-top1000.txt)

... but also small files like

```
pkgs/applications/version-management/sourcehut/default.nix
```

```
$ find pkgs/ -name '*.nix' -not -name test.nix -not -path '*/test/default.nix' | xargs grep -m1 -H -w -e makeScope -e makeScopeWithSplicing -e recurseIntoAttrs | head -n10
pkgs/applications/audio/mopidy/default.nix:lib.makeScope newScope (self: with self; {
pkgs/applications/editors/ed/default.nix:lib.makeScope pkgs.newScope (self:
pkgs/applications/editors/emacs/default.nix:lib.makeScope pkgs.newScope (self:
pkgs/applications/editors/emacs/make-emacs.nix:, recurseIntoAttrs
pkgs/applications/editors/neovim/tests/default.nix:  pkgs.recurseIntoAttrs (
pkgs/applications/editors/vim/plugins/overrides.nix:  nvim-treesitter-parsers = lib.recurseIntoAttrs self.nvim-treesitter.grammarPlugins;
pkgs/applications/editors/vscode/extensions/default.nix:    lib.mapAttrs (_n: lib.recurseIntoAttrs) {
pkgs/applications/graphics/gimp/plugins/default.nix:lib.makeScope pkgs.newScope (self:
pkgs/applications/kde/default.nix:in lib.makeScope libsForQt5.newScope packages
pkgs/applications/maui/default.nix:in lib.makeScope libsForQt5.newScope packages
```

see also [nixpkgs-scope-files.txt](https://github.com/milahu/nixpkgs-package-version-log/raw/main/docs/nixpkgs-scope-files.txt)

presenting the result as static html files is a challenge on its own...
for example, [listing 5000 packages in one html file](https://milahu.github.io/NUR/) is rather slow
it would be easier to produce a sharded sqlite database for offline use

**Comment by lazamar** [comment]
Look, I know the goal is to help, but you are trying to solve something that is not a problem at all, and proposing to add a bunch of complexity on the way.

As I said, this is an approach based on heuristics and I think it is fundamentally flawed.
Nixpkgs works in terms of the result of evaluating the huge nix expression which is the nixpkgs repo.
The fact that commits to the repo follow a convention or that package expression files are usually leaves of the expression is really not firm enough ground to build upon. Conventions are broken all the time. 

You will find that this approach is doomed to derail into fighting endless convention violations. 

This approach really doesn't fit the goals of this project.
