### ISSUE TITLE
installation instructions install the wrong package

### ISSUE THREAD

**Issue by mberndt123** [lazamar/nix-package-versions#41]
Hey,

I need an older version of `kubectl` for work, so I searched for `kubectl` and got to [this page](https://lazamar.co.uk/nix-versions/?package=kubectl&version=1.27.4&fullName=kubectl-1.27.4&keyName=kubectl-convert&revision=976fa3369d722e76f37c77493d99829540d43845&channel=nixpkgs-unstable#instructions).

There it says:
> Install kubectl with nix-env.
> `nix-env -iA kubectl-convert -f https://github.com/NixOS/nixpkgs/archive/976fa3369d722e76f37c77493d99829540d43845.tar.gz`

But this command will install `kubectl-convert` rather than `kubectl`.

**Comment by lazamar** [comment]
This seems to be a problem with this package's Nix derivation.
A package has a name (e.g. `zlib`), a version (e.g. `0.5.4.2`) and a key (e.g. `haskellPackages.zlib`).
Packages are installed by using their key in the derivation object (e.g. `nix-env -iA nixpkgs.haskellPackages.zlib`).

The two packages `kubectl-convert` and `kubectl` have the same value in the `name` field in the nix derivation.
You can see that in the NixOS [search website](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=kubectl-convert).
<img width="1209" alt="image" src="https://github.com/lazamar/nix-package-versions/assets/11493705/6cbd5959-b62c-4bd5-b0b5-37729546d03a">

And also in their derivation [source code](https://github.com/NixOS/nixpkgs/blob/dff0428a45de0523860e783d4d2db7e5fdf61c5c/pkgs/applications/networking/cluster/kubernetes/kubectl.nix#L4).


When packages have the same name and version in a derivation we deduplicate them because this is a known pattern for making multiple versions of a package available in a derivation.

This is the case with Haskell's `zip` package for example, which is available for version `2.0.0` under the keys `haskellPackages.zip` and `haskellPackages.zip_2_0_0`.

For any given revision the nix-package-versions search tool performs deduplication, such that we only show one set of instructions for packages with a given name and version combination.

Given these two `kubectl` packages have the same name and version, one of them is getting cut out.
The right solution here seems to be to reach out to the maintainers and warn them that the `kubectl-convert` package probably should have a different name.
