### ISSUE TITLE
Multiple versions of gcc-wrapper share revisions

### ISSUE THREAD

**Issue by ohunter** [lazamar/nix-package-versions#48]
I encountered this while using the service:
![image](https://github.com/user-attachments/assets/9379a637-653e-4694-a0f5-e28d0c2a9404)

There are more as well. Any idea why this may be the case?

**Comment by lazamar** [comment]
Because the same revision allows you to install different versions of that package.
If you go to https://search.nixos.org/packages you will see that there are actually a bunch of versions in a derivation.
Confusingly they are called different things even though their package `name` is the same.

<img width="975" alt="image" src="https://github.com/user-attachments/assets/174a8f5b-131e-4ab6-b74a-d5aaa0e14ff6">
